services:
  app:
    build: .
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=weather_user
      - MYSQL_PASSWORD=weather_pass
      - MYSQL_DATABASE=weather_db
    depends_on:
      - db
  
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=weather_user
      - MYSQL_PASSWORD=weather_pass
      - MYSQL_DATABASE=weather_db
    volumes:
      - weather_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  weather_data: